### ISSUE TITLE
lxd init does not work with newer versions

### ISSUE THREAD

**Issue by andreasscherbaum** [andreasscherbaum/ansible-lxd#1]
The "echo | lxd init" approach used in this playbook does not work with newer versions, as "lxd init" adds new questions.

A "preseed" option can be used:

```
config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: none
  description: ""
  managed: false
  name: lxdbr0
  type: ""
storage_pools:
- config: {}
  description: ""
  name: default
  driver: dir
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
cluster: null
```
